- name: Stop Broker instances
  tags:
    - broker
    - instance
  shell: "{{ amq_broker_classic_install_dest }}/instances/{{ item.name }}/bin/{{ item.name }} stop"
  ignore_errors: true
  with_items: "{{ amq_broker_classic_instances }}"

- name: Remove Broker instances
  tags:
    - broker
    - instance
  file:
    state: absent
    path: "{{ amq_broker_classic_install_dest }}/instances/{{ item.name }}"
  with_items: "{{ amq_broker_classic_instances }}"

- name: Create Broker instances
  tags:
    - broker
    - instance
  command: "{{ amq_broker_classic_install_dest }}/{{ amq_broker_classic_install_link }}/bin/activemq create {{ amq_broker_classic_install_dest }}/instances/{{ item.name }}"
  register: create_cmd_status
  failed_when: create_cmd_status.rc >= 2
  with_items: "{{ amq_broker_classic_instances }}"

- name: "Configure Broker instances: activemq"
  tags:
    - broker
    - instance
  template:
    src: templates/activemq.xml.j2
    dest: "{{ amq_broker_classic_install_dest }}/instances/{{ item.name }}/conf/activemq.xml"
    mode: 0755
  with_items:
    - "{{ amq_broker_classic_instances }}"


- name: "Configure Broker instances: jetty"
  tags:
    - broker
    - instance
  template:
    src: templates/jetty.xml.j2
    dest: "{{ amq_broker_classic_install_dest }}/instances/{{ item.name }}/conf/jetty.xml"
    mode: 0755
  with_items:
    - "{{ amq_broker_classic_instances }}"


- name: Start Broker instances
  tags:
    - broker
    - instance
  shell: "{{ amq_broker_classic_install_dest }}/instances/{{ item.name }}/bin/{{ item.name }} start"
  register: create_cmd2_status
  failed_when: create_cmd2_status.rc >= 2
  with_items: "{{ amq_broker_classic_instances }}"

